### ISSUE TITLE
Unions

### ISSUE THREAD

**Issue by mikeubell** [openoakland/opendisclosure#279]
Currently when aggregating employer/employee data we aggregate different union locals separately.  We could aggregate all locals from a union together.  For example we have data from a few different locals of the longshoreman's union plus donations that don't specify a local and could be from the national union or from some unspecified local.
Currently we aggregate union PACs with the union they identify with.

We might also want to identify (non-union) PACs in the pie chart.

**Comment by tdooner** [comment]
I think this is done.
