### ISSUE TITLE
Put links to our Candidate Pages on corresponding OaklandWiki/Wikipedia candidate pages 

### ISSUE THREAD

**Issue by evanwolf** [openoakland/opendisclosure#282]
e.g. add links on...  
http://www.oakmayor2014.com/candidates/libby-schaaf/
http://oaklandwiki.org/Libby_Schaaf
http://en.wikipedia.org/wiki/Libby_Schaaf

to 
http://www.opendisclosure.io/candidate/libby-schaaf

**Comment by tdooner** [comment]
I think this is done? Do we not have enough bio information already?
