### ISSUE TITLE
typo on front page - so let's fix it

### ISSUE THREAD

**Issue by evanwolf** [openoakland/opendisclosure#346]
* This is the percentage of money, excluding candidates own contributions and *non-itimized* contributions see the FAQ

should be (correcting spelling and punctuation)

 * This is the percentage of money, excluding candidate’s own contributions and non-itemized contributions. See the FAQ.

suggested (explaining source without leaving page, clarity)

 * Percent of money-raised-from-contributors-giving-an-Oakland-address of a campaign's total funding, leaving out candidate contributions and small non-itemized contributions. See the FAQ.

**Comment by Protosac** [comment]
Fixed. Submitted pull request.
