### ISSUE TITLE
What new disclosure laws/rules should Oakland make?

### ISSUE THREAD

**Issue by evanwolf** [openoakland/opendisclosure#359]
**File more often and sooner.**

Require those who receive and contribute political money to file transactions:

- **Monthly** until one year before the election, then
- **Weekly** until 30 days before the election, then
- **Within 48 hours** until the election.

I've also heard of having 24 hours to report.

**Comment by evanwolf** [comment]
**Continue timely disclosures for officials after an election**

Before the election, we track political money's influence on campaigning and voting. 

After the election, let's track money's influence on governing. 

* What contributors wound up having business before the City Council? 
* Had appointments with the Mayor? 
* Were inspected by the City Auditor? 

We'll ask to open/use more data about officeholder office's calendars and emails. We'll help the public correlate officeholder activity with political contribution data. 

For example, a developer gave to candidates, A, B, and C in the election. We could show the contribution info with post-election activity when she applies for permits in the city, when they speak before the Council, when they have an appointment with a councilmember.

**Comment by tbarreca** [comment]
In Oakland, is the Mayor's calendar a matter of public record?  If not,
that may be a starting place.  It should be by municipal statute, imo.



On Thu, Jan 1, 2015 at 3:58 PM, Phil Wolff <notifications@github.com> wrote:

> *Continue timely disclosures for officials after an election*
>
> Before the election, we track political money's influence on campaigning
> and voting.
>
> After the election, let's track money's influence on governing.
>
>    - What contributors wound up having business before the City Council?
>    - Had appointments with the Mayor?
>    - Were inspected by the City Auditor?
>
> We'll ask to open/use more data about officeholder office's calendars and
> emails. We'll help the public correlate officeholder activity with
> political contribution data.
>
> For example, a developer gave to candidates, A, B, and C in the election.
> We could show the contribution info with post-election activity when she
> applies for permits in the city, when they speak before the Council, when
> they have an appointment with a councilmember.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openoakland/opendisclosure/issues/359#issuecomment-68502868>
> .
>



-- 
Tony Barreca
LinkedIn: http://www.linkedin.com/in/tonybarreca
Skype: tonybarreca
Twitter: tbarreca
Mobile: (510) 710-5864

**Comment by tdooner** [comment]
This would be great to discuss via email.
