### ISSUE TITLE
Q. Do we use a CDN for static images and code?

### ISSUE THREAD

**Issue by evanwolf** [openoakland/opendisclosure#386]
For the less geeky, [Content Distribution Networks](http://en.wikipedia.org/wiki/Content_delivery_network) are services that speed delivery of your site's bits to users while lowering your server's workload.  

We have multiple candidates for content to serve via CDN (things that change infrequenty)...  
- pictures. We have thumbnails and full size photos of candidates, logos, backgrounds 
- Our pie charts aren't interactive that I can see. Can we make charts efficiently on servers - once per candidate for instance - and then just serve up a gif or png? We might lower our payloads and speed up delivery since the chart could now go through a content distribution network. 

We could start with a [free CDN](http://en.wikipedia.org/wiki/Content_delivery_network#Notable_content_delivery_service_providers) and work our way up to a commercial service like Amazon's Cloud Front or Akamai.

**Comment by tbarreca** [comment]
OK.  But I'm curious about the reason why.

CDNs are used when there is a need to handle large volumes of traffic at
speed.  I don't think that's our current profile.

I wouldn't necessarily vote against, but I don't believe in making work
that isn't necessary, either.






On Sun, Mar 22, 2015 at 2:14 PM, Phil Wolff <notifications@github.com>
wrote:

> For the less geeky, Content Distribution Networks
> <http://en.wikipedia.org/wiki/Content_delivery_network> are services that
> speed delivery of your site's bits to users while lowering your server's
> workload.
>
> We have multiple candidates for content to serve via CDN (things that
> change infrequenty)...
>
>    - pictures. We have thumbnails and full size photos of candidates,
>    logos, backgrounds
>    - Our pie charts aren't interactive that I can see. Can we make charts
>    efficiently on servers - once per candidate for instance - and then just
>    serve up a gif or png? We might lower our payloads and speed up delivery
>    since the chart could now go through a content distribution network.
>
> We could start with a free CDN
> <http://en.wikipedia.org/wiki/Content_delivery_network#Notable_content_delivery_service_providers>
> and work our way up to a commercial service like Amazon's Cloud Front or
> Akamai.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openoakland/opendisclosure/issues/386>.
>



-- 
Tony Barreca
LinkedIn: http://www.linkedin.com/in/tonybarreca
Skype: tonybarreca
Twitter: tbarreca
Mobile: (510) 710-5864

**Comment by evanwolf** [comment]
For where the hockey puck will be. We're designing for Open Disclosure California which means serving a population of about 10 million potential users (vs. 0.4) with more visits per user (thanks to better UX and an earlier promotional strategy) and more mobile users (thanks designing for mobile use). 

Thanks for asking for justifications.

**Comment by tbarreca** [comment]
I have never heard of anyone designing to theoretical peak loads.

Look, as far as I'm concerned, if people want to work on this, I would not
argue against it, especially if the model is a freemium one, and we can
experiment at a very basic, i.e., free, level.  It would give us at least a
minimal basis for more realistically estimating probable load.



On Sun, Mar 22, 2015 at 2:40 PM, Phil Wolff <notifications@github.com>
wrote:

> For where the hockey puck will be. We're designing for Open Disclosure
> California which means serving a population of about 10 million potential
> users (vs. 0.4) with more visits per user (thanks to better UX and an
> earlier promotional strategy) and more mobile users (thanks designing for
> mobile use).
>
> Thanks for asking for justifications.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openoakland/opendisclosure/issues/386#issuecomment-84709356>
> .
>



-- 
Tony Barreca
LinkedIn: http://www.linkedin.com/in/tonybarreca
Skype: tonybarreca
Twitter: tbarreca
Mobile: (510) 710-5864

**Comment by tdooner** [comment]
OpenDisclosure would be able to take advantage of a CDN without additional work, but currently does not use one.

We take great pain to serve cache headers that are accurate on every resource, and so theoretically a CDN could provide us great performance boons. However, they also incur weird problems, if we mess up the cache headers or something.

Personally I'm a big fan of CloudFlare, because they give you free wildcard SSL, and we could use that to do stuff like https://oakland.opendisclosure.io.

If you want to set that up, I won't stop you -- you'll need to coordinate with @lla2105 or whoever controls the domain's registration. But as for me, I think it's still a bit premature for that optimization. Hence I'm going to close this now (since the question has been answered) and then we can discuss this later.

**Comment by evanwolf** [comment]
Thanks, Tom!

**Comment by tbarreca** [comment]
+1



On Sun, Mar 22, 2015 at 6:35 PM, Phil Wolff <notifications@github.com>
wrote:

> Thanks, Tom!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openoakland/opendisclosure/issues/386#issuecomment-84745837>
> .
>



-- 
Tony Barreca
LinkedIn: http://www.linkedin.com/in/tonybarreca
Skype: tonybarreca
Twitter: tbarreca
Mobile: (510) 710-5864
