### ISSUE TITLE
The straws are not long enough

### ISSUE THREAD

**Issue by mikeubell** [openoakland/opendisclosure#390]
![](https://lh3.googleusercontent.com/-bYgDG-nKvwg/VRtzDMSznmI/AAAAAAAAD2Y/lyG1Z0mEopY/w782-h587-no/IMG_20150331_204923.jpg)
![img_20150331_205007](https://cloud.githubusercontent.com/assets/6759416/6994749/7bb07640-dad9-11e4-8677-7ff27b7ddba7.jpg)
![img_20150331_205136](https://cloud.githubusercontent.com/assets/6759416/6994750/7def5c6e-dad9-11e4-84cd-cef074c86d15.jpg)
![img_20150331_205232](https://cloud.githubusercontent.com/assets/6759416/6994752/80f04be4-dad9-11e4-989e-7a54fe2a631c.jpg)
![img_20150331_205258](https://cloud.githubusercontent.com/assets/6759416/6994753/822d5542-dad9-11e4-9803-0657d88cc964.jpg)
![img_20150331_210730](https://cloud.githubusercontent.com/assets/6759416/6994754/83e7cb4c-dad9-11e4-95ca-a8aa24a088db.jpg)
![img_20150331_210744](https://cloud.githubusercontent.com/assets/6759416/6994755/89941992-dad9-11e4-9bf4-7b9304e7858d.jpg)
![img_20150331_211036](https://cloud.githubusercontent.com/assets/6759416/6994756/89a6ace2-dad9-11e4-81ab-f13138a377d9.jpg)
![img_20150331_211308](https://cloud.githubusercontent.com/assets/6759416/6994757/89b25452-dad9-11e4-849e-de7172d76b95.jpg)
![img_20150331_211316](https://cloud.githubusercontent.com/assets/6759416/6994760/89b4944c-dad9-11e4-8f46-d67f1f1c1649.jpg)
![img_20150331_211345](https://cloud.githubusercontent.com/assets/6759416/6994758/89b38264-dad9-11e4-95ea-3cd1087f4c87.jpg)
![img_20150331_211404](https://cloud.githubusercontent.com/assets/6759416/6994759/89b425d4-dad9-11e4-8584-2830cb44bd30.jpg)

**Comment by tdooner** [comment]
I have confirmed: the straws were long enough.
