### ISSUE TITLE
Doodle Poll for Next OpenCal Meetup

### ISSUE THREAD

**Issue by bayreporta** [openoakland/opendisclosure#393]
Hey all,

Sorry I couldn't make it to the last meeting. We're trying to nail down our next work session on OpenCal. If you could all take a moment to fill out this Doodle poll, would appreciate. 

It would take place in Oakland.

Cheers~

http://doodle.com/y8xaccgh5r7w3byhduzagnmg/admin#table

**Comment by elinaru** [comment]
Do we know if it's going to be May 2nd or 9th?

**Comment by mikeubell** [comment]
John said the 9th.

**Comment by bayreporta** [comment]
Yea sorry. I was going to send out an email once I confirmed we had a space
with Mai Ling, but yes the 9th.

On Tue, Apr 21, 2015 at 8:47 PM, Michael Ubell <notifications@github.com>
wrote:

> John said the 9th.
>
> > On Apr 21, 2015, at 8:43 PM, Elina Ru <notifications@github.com> wrote:
> >
> > Do we know if it's going to be May 2nd or 9th?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/openoakland/opendisclosure/issues/393#issuecomment-95017981
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openoakland/opendisclosure/issues/393#issuecomment-95018851>
> .
>



-- 
John C. Osborn
Digital Communications Manager
EdSource
707-845-7332
www.johncosborn.com
@bayreporta
Flickr: thereporta

STATEMENT OF CONFIDENTIALITY
The information contained in this electronic message and any attachments
may contain confidential or privileged information intended for the
exclusive use of the addressee(s). If you are not the intended recipient,
please notify the sender by reply e-mail and destroy all copies of the
original message and any attachments. In accordance with Electronic
Communications Privacy Act, 18 U.S.C.§§ 2510-2521.

**Comment by tdooner** [comment]
Hey @bayreporta, thanks for organizing. However, I think we should aim to use GitHub issues for communication related to the source code (design, project planning, etc.). I think this topic would be perfectly appropriate on the `opendisclosure@googlegroups.com` list. Anyone who isn't a member can [request access here](https://groups.google.com/forum/#!forum/open-disclosure).

Also, @lla2105, can you give someone on the west-coast-best-coast owner permissions over that list? I hope all is well with you!
