### ISSUE TITLE
Issues installing locally

### ISSUE THREAD

**Issue by bayreporta** [openoakland/opendisclosure#395]
I'm in the process of installing everything to my Mac. I got to this step in the process:

![screen shot 2015-05-05 at 10 16 02 am](https://cloud.githubusercontent.com/assets/2280866/7478473/eeddaf4a-f30f-11e4-985d-e7c703b263d7.png)

It didn't work. Tried <strong>gem install bundle</strong> and that seemed to work. Not sure if it was correct, however.

Then I got here:

![screen shot 2015-05-05 at 10 22 33 am](https://cloud.githubusercontent.com/assets/2280866/7478589/ab3a3eec-f310-11e4-975d-2a164d0c69d0.png)

I got this error:

<blockquote>sudo -upostgres createuser bayreporta -P
sudo: unknown user: postgres</blockquote>

Any suggestions to help me install this. I'm running postgres through your Option B via terminal. 

NOTE: I have zero postgres or ruby experience.

**Comment by Protosac** [comment]
Be sure bundler is installed on your system. From the application (opendisclosure) folder, you should be able to run `bundle install` and have it install the necessary gems for the app. You can view this page for more specific details on Bundler commands: http://bundler.io/bundle_install.html

The postgres command appears to be a typo. The `-u` is a flag for user. That command tells the terminal to log you into to Postgres as a user named postgres and then create a new user as the name of the user currently logged into the OS. Placing a space between `-u postgres` should fix your issue.

When installing Postgres, it automatically creates a user named `postgres`. Simply make sure the software is installed and that error should go away. Then use the following command to login as the postgres user:

`sudo -i -u postgres`

**Comment by bayreporta** [comment]
That did the trick, I think. The site successfully loads and there doesn't appear to be any problems. 

In the future, all I would have to do to run the v machine is "foreman start" in the directory?

**Comment by bayreporta** [comment]
Also, the machine is running in the terminal instance where I was running the v box. How do I get back to the prompt so I can shut it down? Thanks

**Comment by bayreporta** [comment]
NVM got it thanks
